language: node_js
node_js:
  - 12
  - 14
  - 16
script:
  - echo 'Installing dependencies...'
  - npm install
  - echo 'Creating a build...'
  - npm run build
  - echo 'Running tests...'
  - npm test
  - echo 'Completed!'
